name: Build and Release

on:
  push:
    branches: [ "fix-windows" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-20.04
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build script for Linux
      if: ${{ !(matrix.os == 'windows-latest') }}
      run: >
        ./build_samples.sh
        --no-tests
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      if: ${{ matrix.os == 'windows-latest' }}
      id: runvcpkg
      with:
        # The vcpkg.json file, which will be part of cache key computation.
        vcpkgJsonGlob: '**/samples/cloudfuse_plugin/vcpkg.json'
    
    - name: Run build script for Windows
      shell: powershell
      if: ${{ matrix.os == 'windows-latest' }}
      run: >
        .\build_samples.bat
        --no-tests
        --debug

    - name: Package Artifacts Linux
      if: ${{ Contains(matrix.os, 'ubuntu') }}
      run: |
        mkdir release
        mv ../nx-lyve-cloud-plugin-build/cloudfuse_plugin/*.so release/cloudfuse_plugin.so
        cp ./setup_fuse_allow_other.sh release/
        zip -r nx-lyve-plugin-${{ matrix.os }}.zip release

    - name: Package Artifacts Windows
      shell: powershell
      if: ${{ Contains(matrix.os, 'windows') }}
      run: |
        mkdir release
        mv ..\nx-lyve-cloud-plugin-build\cloudfuse_plugin\Debug\*.dll release\cloudfuse_plugin.dll
        Compress-Archive release nx-lyve-plugin-${{ matrix.os }}.zip

    - name: Archive production artifacts Ubuntu
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: nx-lyve-plugin-${{ matrix.os }}.zip
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build-ubuntu-20.04/*
          build-ubuntu-22.04/*
          build-windows/*
